trigger:
- '*'

variables:
- group: 'tf-example-variables'

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: |
      # Exit when any command returns a failure status.
      set -e
      export ARM_CLIENT_ID="$(ARM_CLIENT_ID)"
      export ARM_CLIENT_SECRET="$(ARM_CLIENT_SECRET)"
      export ARM_TENANT_ID="$(ARM_TENANT_ID)"
      export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"

      # Initialize Terraform.
      terraform init -input=false
      # Apply the Terraform plan.
      terraform apply -input=false -var-file="values.tfvars" -auto-approve

    name: 'RunTerraform'
    displayName: 'Run Terraform'
  - publish: $(System.DefaultWorkingDirectory)/terraform.tfstate
    artifact: StateFile
