# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: 'tf-example-variables'

pool:
  vmImage: 'ubuntu-latest'

steps:
- download: current
  artifact: Tfstate
  patterns: '**/terraform.tfstate'
- script: |
    #Initializing Terraform
    terraform init
    #Destroying infra
    terraform destroy
    
  name: 'RunTerraform'
  displayName: 'Run Terraform'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
