# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  tf-ex-variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- download: current
  artifact: Tfstate
  patterns: '**/terraform.tfstate'
- script: terraform destroy
  
